In [2]:
import gcamreader
import pandas as pd

Select the scenarios and the query wanted

In [3]:
dbpath = "/lustre/home/2501112459/Desktop/GCAM_Workspace/gcam-hpc-PKU/gcam-scratch/exe_0/db"
dbfile = "database_basexdb"
conn = gcamreader.LocalDBConn(dbpath, dbfile)

Failed to validate database: /lustre/home/2501112459/Desktop/GCAM_Workspace/gcam-hpc-PKU/gcam-scratch/exe_0/db/database_basexdb

OSError: Failed to validate database: /lustre/home/2501112459/Desktop/GCAM_Workspace/gcam-hpc-PKU/gcam-scratch/exe_0/db/database_basexdb

In [3]:
queries = gcamreader.parse_batch_query("/lustre/home/2501112459/Desktop/GCAM_Workspace/gcam-hpc-PKU/gcam-hpc-tools/query-tools/i_queries_xml/steel-tech-protofolio-query.xml")
[q.title for q in queries]

['iron and steel production by tech',
 'CO2 emissions by tech (excluding resource production)',
 'iron and steel inputs by tech (energy and feedstocks)',
 'industry final energy by tech and fuel',
 'traded iron and steel',
 'regional iron and steel sources',
 'CO2 emissions by sector (excluding resource production)']

In [4]:
conn.runQuery(queries[0])

,Units,scenario,region,sector,subsector,technology,output,Year,value
0,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Africa_Eastern,iron and steel,BLASTFUR,BLASTFUR,iron and steel,2021,0.002401
1,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Africa_Eastern,iron and steel,BLASTFUR,BLASTFUR,iron and steel,2025,0.066106
2,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Africa_Eastern,iron and steel,BLASTFUR,BLASTFUR,iron and steel,2030,0.271419
3,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Africa_Eastern,iron and steel,BLASTFUR,BLASTFUR,iron and steel,2035,0.709174
4,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Africa_Eastern,iron and steel,BLASTFUR,BLASTFUR,iron and steel,2040,1.426537
...,...,...,...,...,...,...,...,...,...
3467,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Ukraine,iron and steel,EAF with scrap,EAF with scrap,iron and steel,2080,1.692525
3468,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Ukraine,iron and steel,EAF with scrap,EAF with scrap,iron and steel,2085,1.593132
3469,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Ukraine,iron and steel,EAF with scrap,EAF with scrap,iron and steel,2090,1.490082
3470,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Ukraine,iron and steel,EAF with scrap,EAF with scrap,iron and steel,2095,1.381465
3471,Mt,"Policy,date=2025-25-7T21:49:29+08:00",Ukraine,iron and steel,EAF with scrap,EAF with scrap,iron and steel,2100,1.267246